### ISSUE TITLE
Packaging for Debian/Ubuntu

### ISSUE THREAD

**Issue by hakavlad** [facebookincubator/oomd#103]
Well, you understand.

**Comment by bureado** [comment]
A Debian [package](https://tracker.debian.org/pkg/oomd) is in `testing` and `sid`, and looks like [Ubuntu is coming](https://launchpad.net/ubuntu/+source/oomd/0.2.0-2), too. It looks like GCC 8 is kind of a requirement, so it's not building in `bionic`.

**Comment by hakavlad** [comment]
Thank you!
