### ISSUE TITLE
Figure out how to make installed binary name 'oomd'

### ISSUE THREAD

**Issue by danobi** [facebookincubator/oomd#11]
`oomd` is currently installed as `/usr/local/bin/oomd_bin`. This is because there _must_ be a `oomd` directory in the build directory. The tests are wired to look in `./oomd/fixtures/...` because of a FB tooling limitation. Therefore, the binary executable was renamed to `oomd_bin`.

There _has_ to be a way to change the name of the installed binary. I'm not sure running a script and renaming the binary is a good idea because then `ninja uninstall` might not clean up everything.

**Comment by SauravPrakash98** [comment]
I want to attempt this, please can you explain a bit more.

**Comment by danobi** [comment]
@SauravPrakash98 , sure. a21a58461043d76 adds install support to the meson build. When oomd gets installed via `sudo ninja install`, oomd's name is `/usr/local/bin/oomd_bin`. I'd be great if the name was `/usr/local/bin/oomd`.

**Comment by gurungrahul2** [comment]
I have a question, why exactly can't we configure it to install as /usr/local/bin/oomd , is it because system will look at it like tests ?

**Comment by SauravPrakash98** [comment]
@gurungrahul2 In meson.build after you change the name of the executable from ```oomd_bin``` to ```oomd```, then running ```meson build && ninja test -C build``` is unable to create the binary in the ```build``` folder

**Comment by Hyperion101010** [comment]
it is easy just change the executable name and then it installs as oomd_bin 
it is not a bug just a change in file name :) happy to apply patch .

**Comment by danobi** [comment]
@Hyperion101010 I'm not sure what you mean, could you supply a patch?

**Comment by Hyperion101010** [comment]
here are some updates i ran the build ,so it installed correctly "the oomd named binary in the usr/local/bin" but when i went to run the binary it gave permission error ,
----------------------------------the output message------------------------------------------------------
 open: Permission denied
(inl) [../Log.cpp:88] Unable to open outfile (default=/dev/kmsg), not logging
terminate called after throwing an instance of 'std::system_error'
  what():  Permission denied
Aborted (core dumped)
----------------------------------------------------------------------------------------------------------------
now i looked for it in log.cpp it was a file open(permission) issue ,so i ran it in superuser ,but it gave fatal error 
resulting in core dump
i'll run this with systrace and then get back to you with updates

**Comment by Hyperion101010** [comment]
![screenshot from 2018-09-20 10-50-09](https://user-images.githubusercontent.com/32175777/48396206-a7dc7900-e73f-11e8-9b19-fab8bbdbcdd6.png)
--------->on line 54 i changed name to oomd from oomd_bin

**Comment by danobi** [comment]
Ignoring the changed meson files (which should not be part of the commit), it looks like you changed the executable target from `oomd_bin` to `oomd`. I'm not sure this will work. When I build with that change, I get this output:

```
$ git --no-pager diff
diff --git a/meson.build b/meson.build
index 8c53421..217b0e0 100644
--- a/meson.build
+++ b/meson.build
@@ -51,7 +51,7 @@ oomd_lib = library('oomd',
                    cpp_args : cpp_args,
                    install: true,
                    dependencies : deps)
-executable('oomd_bin',
+executable('oomd',
            files('Main.cpp'),
            include_directories : inc,
            cpp_args : cpp_args,

$ ninja
[1/13] Linking target oomd.
FAILED: oomd 
c++  -o oomd 'oomd@exe/Main.cpp.o' -Wl,--no-undefined -Wl,--as-needed -Wl,--start-group liboomd.so /usr/lib64/libjsoncpp.so -Wl,--end-group -pthread '-Wl,-rpath,$ORIGIN/:XXXXXXXX' -Wl,-rpath-link,/home/dlxu/dev/oomd/biuld/  
/bin/ld: cannot open output file oomd: Is a directory
collect2: error: ld returned 1 exit status
[6/13] Linking target oomd_killer_tests.
ninja: build stopped: subcommand failed.
```

**Comment by Hyperion101010** [comment]
can you run the install in a virtual env

**Comment by Hyperion101010** [comment]
now try running it .
took me two days but its fine i did something ,
the issue was in meson build 
1>if we gave it name as "oomd" then there was a directory created for fixtures 
thus now when main.cpp was running it saw it as a directory rather than a oomd binary
------------------------solution---------------------------------------------------
2>what i did was renamed the mkdir to make "oomd_fix" rather than "oomd" file for fixtures so it now doesn't conflicts with it and creates a binary named oomd 
feeling great :)

**Comment by danobi** [comment]
@Hyperion101010 That works for creating the executable but it would break the tests. Unfortunately the fixtures have to stay in a folder named `oomd`. It's kind of crappy, I know. I was really hoping there was a meson option to install the binary as a different name.

**Comment by danobi** [comment]
I don’t think wrapping the build system with what sounds like another build system is a good idea. I think the correct way to do this would be to find the correct meson option or try to implement this feature in meson itself. Or if possible, generate the executable inside another directory so there’s no name collisions.

**Comment by ufo19890607** [comment]
Hi, all , I'm sure that I've setup the jsoncpp and ninja, but when I run 'meson build && ninja -C build'

[root@bogon oomd]# meson build && ninja -C build
The Meson build system
Version: 0.47.2
Source dir: /home/ufo/oomd
Build dir: /home/ufo/oomd/build
Build type: native build
Project name: oomd
Project version: 0.1.0
Native C++ compiler: c++ (gcc 4.8.5 "c++ (GCC) 4.8.5 20150623 (Red Hat 4.8.5-16)")
Build machine cpu family: x86_64
Build machine cpu: x86_64
Found pkg-config: /usr/bin/pkg-config (0.27.1)

meson.build:72:0: ERROR:  Native dependency 'jsoncpp' not found

A full log can be found at /home/ufo/oomd/build/meson-logs/meson-log.txt

**Comment by RunningDroid** [comment]
Sorry for bumping an old issue, but it looks like https://github.com/facebookincubator/oomd/commit/33c4bda97209e8be3f6702bc29bd692a8d0b5096 resolves this
