### ISSUE TITLE
/sys/fs/cgroup is not a valid cgroup2 filesystem

### ISSUE THREAD

**Issue by Pushergene** [facebookincubator/oomd#128]
/sys/fs/cgroup> ls
blkio  cpuacct      cpuset   freezer  memory   net_cls,net_prio  perf_event  rdma     unified
cpu    cpu,cpuacct  devices  hugetlb  net_cls  net_prio          pids        systemd

How can i fix it? I compiled from source, using OpenSUSE Tumbleweed with psi=1. 
https://github.com/openSUSE/kernel-source/blob/master/config/x86_64/default

 is there something which does prevent it?

**Comment by hakavlad** [comment]
Maybe you use mixed cgroup hierarchy. Could you provide `cat /proc/self/cgroup`?

**Comment by hakavlad** [comment]
See also https://github.com/facebookincubator/oomd/blob/master/docs/production_setup.md#kernel-command-line

**Comment by cdown** [comment]
oomd requires cgroup v2, but the hierarchy you're showing is cgroup v1.

You can enable tell systemd to use the new unified hierarchy and disable the old controllers with `cgroup_no_v1=all` on the kernel command line.

**Comment by Pushergene** [comment]
> oomd requires cgroup v2, but the hierarchy you're showing has resource control under cgroup v1.
> 
> You can enable tell systemd to use the new unified (v2) hierarchy, and simultaneously disable the old controllers with `cgroup_no_v1=all` on the kernel command line.
Can that be dangerous? i mean it probably has a readon why its not enabled by default.

**Comment by cdown** [comment]
I'm gonna go ahead and close this one, I'm pretty sure the answer here is just to use cgroup v2, as required :-)
