### ISSUE TITLE
memleaks ???

### ISSUE THREAD

**Issue by jelmd** [facebookincubator/oomd#158]
Each time a detection group/action fires, oomd RSS mem usage (`/sys/fs/cgroup/system.slice/oomd.service/memory.current`) rises in my test environment ~ 400..500 KiB. Are there any mem leaks?

**Comment by lnyng** [comment]
We are not aware of any memory leak as for now. It's hard to tell if what you observe is a memory leak without more details. If this RSS rise accumulates to some unreasonable amount, please show some script to reproduce so we can investigate.

**Comment by jelmd** [comment]
ok, thanx. Haven't had the time to do deeper analysis, yet (and because I'm not a C++ expert it is hard for me to find out anything). Anyway, just asking to avoid waisting resources by digging into stuff, which has been already solved.
