### ISSUE TITLE
No timestamps in oomd output

### ISSUE THREAD

**Issue by davidspencerward** [facebookincubator/oomd#165]
We are logging the output of oomd to /var/log/oomd.log. Here is the beginning of the log file:

root@echo:/sys/fs/cgroup# cat /var/log/oomd.log 
oomd running with conf_file=/etc/oomd/oomd.json interval=5
[../src/oomd/config/ConfigTypes.cpp:42]  0 PrekillHooks=
[../src/oomd/config/ConfigTypes.cpp:61]  3 Rulesets=
[../src/oomd/config/ConfigTypes.cpp:65]    Ruleset=system overview
[../src/oomd/config/ConfigTypes.cpp:69]      DropIn=
[../src/oomd/config/ConfigTypes.cpp:71]        Detectors=0
[../src/oomd/config/ConfigTypes.cpp:73]        Actions=0
[../src/oomd/config/ConfigTypes.cpp:75]        DisableOnDrop=0
[../src/oomd/config/ConfigTypes.cpp:79]      SilenceLogs=engine
[../src/oomd/config/ConfigTypes.cpp:83]      DetectorGroup=records system stats
[../src/oomd/config/ConfigTypes.cpp:88]        Detector=dump_cgroup_overview
[../src/oomd/config/ConfigTypes.cpp:90]          Args=
[../src/oomd/config/ConfigTypes.cpp:95]            cgroup=system.slice
[../src/oomd/config/ConfigTypes.cpp:104]     Action=continue

So we have file names and line numbers but there are no timestamps! These missing timestamps are really important when you try to correlate OOM events with the other log files in the system.

Is there some reason why timestamps have been omitted from the oomd output? It seems a pretty standard thing in logging. And, can it be turned on somehow? I didn't see a way without patching the source code myself.

Thanks,

David

**Comment by lnyng** [comment]
You could run oomd as a systemd service and use rsyslog to add timestamp and other useful prefixes.
