### ISSUE TITLE
Code of Conduct "full text" link broken

### ISSUE THREAD

**Issue by cemeyer** [facebookincubator/oomd#2]
The [URL targeted by the "full text" link](https://code.facebook.com/pages/876921332402685/open-source-code-of-conduct) in [CODE_OF_CONDUCT.md](https://github.com/facebookincubator/oomd/blob/master/CODE_OF_CONDUCT.md) leads to a "The content you’re looking for is not available at this URL" page.

**Comment by danobi** [comment]
Link is fixed now. Thanks for the report.
