### ISSUE TITLE
Write extensive howto documentation

### ISSUE THREAD

**Issue by danobi** [facebookincubator/oomd#22]
* how to install
* how to read logs
* how to write plugins
* how to customize common behaviors

**Comment by Hyperion101010** [comment]
hey man i can do that in my free time :)
but what should i follow like any rules ?
also i pulled the repo you can check

**Comment by danobi** [comment]
I'll be writing this after I land the oomd2 PR. It's gonna be a brain dump of information so it should probably come from me.

**Comment by danobi** [comment]
Done. Docs are in `docs/`

**Comment by hakavlad** [comment]
>how to read logs

How to read logs? I cannot find it in docs.

**Comment by danobi** [comment]
> How to read logs? I cannot find it in docs.

Logs are printing to stderr. If oomd is attached to a terminal, you should see it. If it's being managed by systemd, you can look via `journalctl -u $OOMD_SERVICE_NAME`.

**Comment by hakavlad** [comment]
@danobi Thank you!
