### ISSUE TITLE
Handle case where cgroups disappear in `Oomd::updateContext()`

### ISSUE THREAD

**Issue by danobi** [facebookincubator/oomd#25]
Between the time we verify a cgroup exists and has all the right controllers enabled and the time we examine the actual controller files, the cgroup can go away. In other words, between loading all the existing cgroups [here](https://github.com/facebookincubator/oomd/blob/master/Oomd.cpp#L102) and actually inspecting the state [here](https://github.com/facebookincubator/oomd/blob/master/Oomd.cpp#L106-L109), the latter files can disappear. This usually happens for short lived processes. We currently eat a segfault when we hit this race.

I think we can have all the `Fs::read*Pressure` calls throw an exception if the file is missing. `updateContext` can catch any exceptions and abort updating the current cgroup.

**Comment by Hyperion101010** [comment]
https://github.com/Hyperion101010/oomd
have a look

**Comment by danobi** [comment]
Can you open a pull request so I can leave comments?

**Comment by Hyperion101010** [comment]
danobi is my 26 patch submitted ?
