### ISSUE TITLE
Add a config checker cmd line option

### ISSUE THREAD

**Issue by danobi** [facebookincubator/oomd#36]
oomd configs are first parsed and then compiled. If the config is invalid, oomd currently crashes. This is fine-ish but also suboptimal. It would be nice if users could run `oomd --check /my/config/file` and oomd would exit 0 on "good" config and exit non-zero on "bad" config, along with the relevant error messages.

`Oomd::Config2::compile` does all the error checking. You'll probably want to look to make changes in Main.cpp and Oomd.cpp.

**Comment by Hyperion101010** [comment]
look good !

**Comment by Hyperion101010** [comment]
we must try for optimizatio's

**Comment by Hyperion101010** [comment]
Now can I start on this one?

**Comment by Hyperion101010** [comment]
solved it! , I'll upload it,  but I can't figure out how can I have one more branch in the fork.

**Comment by andrew880** [comment]
resolved
