### ISSUE TITLE
Create a sane desktop linux configuration

### ISSUE THREAD

**Issue by danobi** [facebookincubator/oomd#38]
This should be a good "fits most" configuration to prevent unresponsive desktop systems.

This issue will track progress.

**Comment by danobi** [comment]
First I had to turn on systemd's cgroup2 only support by adding `systemd.unified_cgroup_hierarchy` to my kernel boot options.

**Comment by danobi** [comment]
We're missing a couple of pieces for this to happen:
* systemd has a cgroup2 bug: https://github.com/systemd/systemd/pull/10876 . It's since been fixed but I don't believe the patch has made its way into a release yet
* Linux 4.20 contains the PSI patches. That also has not been released.

Note that these are both out of my control, so expect more progress here in a couple of weeks.

**Comment by danobi** [comment]
#40 should be valid, but is untested on my home machine. (It has been tested on developer machines at FB, though, with minor modifications).

**Comment by Hyperion101010** [comment]
so will that patch , eliminate this bug ?

**Comment by nomego** [comment]
Ok so the systemd boot option is needed, what's the effect of the cgroup2 bug and how do we now when it's a release?
Are the PSI patches merged and available in an 4.20 RC ?

**Comment by danobi** [comment]
@nomego IIRC, the systemd bug resulted in the memory controller not being delegated to cgroups in `user.slice`. The bug doesn't happen all the time but it happened often enough at FB.

The PSI patches have been merged and I do believe they're in 4.20 RC.

**Comment by danobi** [comment]
@nomego IIRC, the systemd bug resulted in the memory controller not being delegated to cgroups in `user.slice`. The bug doesn't happen all the time but it happened often enough at FB.

The PSI patches have been merged and I do believe they're in 4.20 RC.

**Comment by danobi** [comment]
Linux 4.20 got packaged for arch linux and I think systemd is prepping a v240 release. I'm going to start working on this again since we are unblocked.

**Comment by danobi** [comment]
8d21de7e6b3 has a basic systemd configureation
