### ISSUE TITLE
oomd should respect OOMScore

### ISSUE THREAD

**Issue by disaster123** [facebookincubator/oomd#57]
Currently oomd also kill processes or groups which have an OOMScore of -1000. It would be nice to ignore those. Another possibility would be to define cgroups which should be ignored.

**Comment by danobi** [comment]
Yeah, the blacklist is on my todo list. Internally we have a modified plugin that does blacklisting but I need to generalize it a bit more.

As for the oom_score, that's probably a no-go. A lot of oomd's value comes from the explicit, one-location configuration, and watching oom_score goes against that idea.

**Comment by disaster123** [comment]
regarding oom_score you're right that makes no sense. But a blacklist would be really useful.

**Comment by danobi** [comment]
Filed #58 to track
