### ISSUE TITLE
Create generic blacklist mechanism for arbitrary cgroups

### ISSUE THREAD

**Issue by danobi** [facebookincubator/oomd#58]

**Comment by disaster123** [comment]
Is there any workaround available? I would never ever like to kill the database service but it is part of the system.slice

**Comment by danobi** [comment]
Yes, you could move your database service to another slice that oomd isn't monitoring, like `oomd_exempt.slice`.

Still need to work on this feature at some point...

**Comment by lnyng** [comment]
Use the "Exists" plugin to do this
