### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by hakavlad** [facebookincubator/oomd#84]
Please make CHANGELOG.md

**Comment by danobi** [comment]
Yeah, we probably should.

**Comment by hakavlad** [comment]
0.2.0 released, but there is no changelog. How do I write news?

**Comment by danobi** [comment]
I will probably start generating changelogs based on git history.

For now, you can see https://github.com/facebookincubator/oomd/compare/v0.1.0...v0.2.0 for the changes.

**Comment by filbranden** [comment]
In other projects I manage, I tend to point people at the commit log instead:

https://github.com/facebookincubator/oomd/compare/v0.1.0...v0.2.0

Oh, I noticed this is just what @danobi just said :rofl:

Maybe let's stick to that and close this issue?
